name: Examples

on:
  push:
    branches:
      - main

jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: canidae-solutions/lix-quick-install-action@v2
      - run: nix-build --version

  flakes-simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: canidae-solutions/lix-quick-install-action@v2
      - name: nix build
        run: nix build ./examples/flakes-simple
      - name: hello
        run: ./result/bin/hello
